# Используем официальный образ PostgreSQL
FROM postgres:latest

# Устанавливаем переменные окружения
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydatabase

# Открываем порт
EXPOSE 5432