version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spark:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./spark_job.py:/app/spark_job.py
      - ./sqlite-jdbc-3.47.1.0.jar:/opt/spark/jars/sqlite-jdbc-3.47.1.0.jar
      - ./postgresql-42.7.3.jar:/opt/spark/jars/postgresql-42.7.3.jar
      - ./chinook.db:/app/chinook.db 
    depends_on:
      - postgres

volumes:
  postgres_data: